on:
  workflow_call:
    inputs:
      arch_tags:
        type: string
        required: true

permissions:
  contents: read

jobs:
  merge_arch_tags:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Check out code
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Merge Arch Tags
        id: merge
        run: make ci-merge-arch-tags ARCH_TAGS=${{ inputs.arch_tags }}